name: Maj veille IA Militaire

on:
  schedule:
    - cron: "0 6 * * *"   # Tous les jours à 06:00 UTC
  workflow_dispatch:

# Autorise le push vers gh-pages avec GITHUB_TOKEN
permissions:
  contents: write

env:
  DAYS_WINDOW: "30"            # Fenêtre glissante (en jours)
  OFFLINE_TRANSLATION: "true"  # Traduction offline EN->FR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Cache des modèles Argos (~200 Mo max)
      - name: Cache Argos models
        id: cache-argos
        uses: actions/cache@v4
        with:
          path: ~/.local/share/argos-translate/packages
          key: argos-en-fr-model-v1

      # Installe EN->FR si non présent en cache
      - name: Install Argos EN→FR model
        if: steps.cache-argos.outputs.cache-hit != 'true'
        run: |
          python - <<'PY'
          from argostranslate import package
          available = package.get_available_packages()
          for p in available:
              if p.from_code == "en" and p.to_code == "fr":
                  package.install_from_path(p.download())
                  print("Installed:", p)
                  break
          PY

      - name: Run veille script
        env:
          DAYS_WINDOW: ${{ env.DAYS_WINDOW }}
          OFFLINE_TRANSLATION: ${{ env.OFFLINE_TRANSLATION }}
        run: python veille_ia.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
