name: build

on:
  push:
    branches: [ "main" ]
    paths:
      - "veille_ia.py"
      - ".github/workflows/**"
      - "docs/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    env:
      # ---- Paramètres de la veille ----
      DAYS_WINDOW: "60"          # fenêtre glissante (jours)
      RELEVANCE_MIN: "0.35"      # seuil de pertinence contextuelle
      OFFLINE_TRANSLATION: "1"   # activer la traduction offline EN->FR

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements (pinned)
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r .github/workflows/requirements.txt

      - name: Cache Argos models
        id: cache-argos
        uses: actions/cache@v4
        with:
          path: ~/.local/share/argos-translate/packages
          key: Linux-argos-cache-v1

      - name: Install Argos EN→FR model (idempotent via API)
        run: |
          python - <<'PY'
          from argostranslate import package, translate

          # Si déjà installé, on sort proprement
          for p in package.get_installed_packages():
              if p.from_code == "en" and p.to_code == "fr":
                  print("✅ Modèle EN→FR déjà installé")
                  raise SystemExit(0)

          print("⇣ Téléchargement modèle EN→FR…")
          package.update_package_index()
          available = package.get_available_packages()
          candidates = [p for p in available if p.from_code == "en" and p.to_code == "fr"]
          if not candidates:
              raise SystemExit("❌ Aucun package EN→FR disponible dans l’index Argos.")
          # prend la version la plus récente si plusieurs
          candidates.sort(key=lambda p: getattr(p, "version", ""), reverse=True)
          pkg = candidates[0]
          package.install_from_path(package.download_package(pkg))

          # Smoke test
          translate.load_installed_languages()
          langs = translate.get_installed_languages()
          en = next(l for l in langs if l.code == "en")
          fr = next(l for l in langs if l.code == "fr")
          tr = en.get_translation(fr)
          print("Test:", tr.translate("test"))
          print("✅ Modèle Argos EN→FR installé")
          PY

      - name: Run veille script
        run: |
          python veille_ia.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
