name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "veille_ia.py"
      - ".github/workflows/**"
  schedule:
    - cron: "0 */6 * * *"  # toutes les 6h

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # nécessaire pour gh-pages
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install deps
        run: pip install -r .github/workflows/requirements.txt

      - name: Restore Argos cache
        uses: actions/cache@v4
        with:
          path: ~/.local/share/argos-translate
          key: ${{ runner.os }}-argos-cache-v1

      - name: Preinstall Argos EN→FR
        run: |
          python - <<'PY'
          from argostranslate import package, translate
          package.update_package_index()
          pkgs = package.get_available_packages()
          p = next(p for p in pkgs if p.from_code=="en" and p.to_code=="fr")
          path = p.download()
          package.install_from_path(path)
          # Sanity check
          langs = translate.get_installed_languages()
          assert any(l.code=="en" for l in langs) and any(l.code=="fr" for l in langs)
          print("Argos EN→FR OK")
          PY

      - name: Save Argos cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ~/.local/share/argos-translate
          key: ${{ runner.os }}-argos-cache-v1

      - name: Run generator
        env:
          DAYS_WINDOW: "45"
          RELEVANCE_MIN: "0.18"
          MAX_SUMMARY_CHARS: "320"
          OFFLINE_TRANSLATION: "1"
        run: python veille_ia.py

      # Déploiement : branche gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
