name: Maj veille IA Marine (hardened)

on:
  schedule:
    - cron:  "0 6 * * *"   # Tous les jours à 06:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install feedparser pandas

      - name: Run script veille IA
        env:
          GEN_ENDPOINT: ${{ secrets.GEN_ENDPOINT }}
          GEN_TOKEN: ${{ secrets.GEN_TOKEN }}
        run: python veille_ia.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
