name: build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      - name: Cache Argos models
        uses: actions/cache@v4
        with:
          path: ~/.local/share/argos-translate
          key: argos-models-en-fr-v1

      - name: Ensure Argos EN→FR model installed
        env:
          OFFLINE_TRANSLATION: "1"
        run: |
          python - <<'PY'
          import os
          if os.getenv("OFFLINE_TRANSLATION","1")!="1":
              raise SystemExit(0)
          try:
              from argostranslate import translate, package
              langs = translate.get_installed_languages()
              en = next((l for l in langs if l.code=="en"), None)
              fr = next((l for l in langs if l.code=="fr"), None)
              if not (en and fr):
                  package.update_package_index()
                  pkgs = package.get_available_packages()
                  p = next((p for p in pkgs if p.from_code=="en" and p.to_code=="fr"), None)
                  if p:
                      path = p.download()
                      package.install_from_path(path)
              print("Argos ready.")
          except Exception as e:
              print("Argos not ready:", e)
          PY

      - name: Run generator
        env:
          DAYS_WINDOW: "45"
          RELEVANCE_MIN: "0.30"
          OFFLINE_TRANSLATION: "1"
        run: |
          python veille_ia.py

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
