name: Maj veille IA Marine

on:
  schedule:
    - cron: "0 6 * * *"         # Tous les jours à 06:00 UTC
  workflow_dispatch:

# IMPORTANT pour pouvoir pousser sur gh-pages
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (no requirements.txt)
        run: |
          python -m pip install --upgrade pip
          pip install feedparser "argostranslate>=1.9.0"

      - name: Install Argos EN→FR model
        run: |
          python - <<'PY'
          from argostranslate import package
          import urllib.request
          url = "https://argosopentech.nyc3.digitaloceanspaces.com/argospm/translate-en_fr-1_9.argosmodel"
          urllib.request.urlretrieve(url, "en_fr.argosmodel")
          package.install_from_path("en_fr.argosmodel")
          print("✅ Argos EN→FR installed")
          PY

      - name: Run veille script
        env:
          # Active la traduction offline dans veille_ia.py
          OFFLINE_TRANSLATION: "1"
          # Paramètres de fenêtre et scoring contextuel (ajuste si besoin)
          DAYS_WINDOW: "45"
          RELEVANCE_MIN: "0.50"
          HALF_LIFE_DAYS: "20"
        run: python veille_ia.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
