name: Maj veille IA Marine

on:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * *'   # tous les jours à 06:30 UTC
  push:
    branches: [ main ]

permissions:
  contents: write   # pour pousser sur gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # --- Paramètres de ta veille ---
      DAYS_WINDOW: '45'               # fenêtre glissante (jours)
      RELEVANCE_MIN: '0.50'           # seuil de pertinence contextuelle
      MAX_SUMMARY_FR_CHARS: '280'     # longueur max des résumés FR
      OFFLINE_TRANSLATION: '1'        # activer la traduction Argos offline

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      # Cache des modèles Argos (plus rapide et moins de bande passante)
      - name: Cache Argos models
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/argos-translate
          key: ${{ runner.os }}-argos-${{ hashFiles('.github/workflows/requirements.txt') }}

      # >>> NOUVELLE ÉTAPE : installation via le catalogue officiel Argos
      - name: Install Argos EN→FR model
        run: |
          python - <<'PY'
          from argostranslate import package, translate
          # Récupère les paquets disponibles (catalogue officiel)
          available_packages = package.get_available_packages()
          # Cherche EN->FR
          en_fr = next(p for p in available_packages if p.from_code == "en" and p.to_code == "fr")
          print(f"⇣ Téléchargement modèle EN→FR {en_fr.package_version}…")
          pkg_path = en_fr.download()
          package.install_from_path(pkg_path)
          translate.load_installed_packages()
          print("✅ Modèle Argos EN→FR installé")
          PY

      - name: Run veille script
        run: |
          python veille_ia.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
