name: build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show requirements
        run: |
          echo "=== .github/workflows/requirements.txt ==="
          cat .github/workflows/requirements.txt || true
          echo "========================================="

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      - name: Run generator
        env:
          DAYS_WINDOW: "60"
          RELEVANCE_MIN: "0.28"
          OFFLINE_TRANSLATION: "0"
        run: |
          python veille_ia.py

      - name: Deploy to gh-pages
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
