name: Maj veille IA Marine (offline)

on:
  schedule:
    - cron: "0 6 * * *"   # Tous les jours à 06:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # <-- La modification est ici : requirements.txt lu dans .github/workflows/
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      # Cache des modèles Argos (accélère les runs suivants)
      - name: Cache Argos models
        uses: actions/cache@v4
        with:
          path: ~/.local/share/argos-translate
          key: argos-${{ runner.os }}-v1

      # Installation du modèle EN -> FR pour Argos
      - name: Install Argos EN→FR model
        run: |
          python - <<'PY'
          from argostranslate import package
          import os
          os.makedirs(os.path.expanduser("~/.local/share/argos-translate/packages"), exist_ok=True)
          available = package.get_available_packages()
          pkg = next((p for p in available if p.from_code == "en" and p.to_code == "fr"), None)
          if pkg:
              path = pkg.download()
              package.install_from_path(path)
          print("Argos EN->FR ready")
          PY

      # (Optionnel) Cache du fichier de traduction si tu en utilises un local
      - name: Cache translation map
        uses: actions/cache@v4
        with:
          path: translation_cache.json
          key: translation-cache-${{ github.run_id }}
          restore-keys: |
            translation-cache-

      - name: Run veille script
        env:
          # Fenêtre glissante en jours (ex: 30)
          DAYS_WINDOW: "30"
          # Active la traduction offline
          OFFLINE_TRANSLATION: "1"
        run: python veille_ia.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          # optionnel :
          # user_name: github-actions[bot]
          # user_email: 41898282+github-actions[bot]@users.noreply.github.com
